name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-11-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer cython
          pip install -r requirements.txt

      - name: Build APK
        run: |
          sudo apt install -y build-essential ccache libncurses5 libstdc++6 libssl-dev libffi-dev libsqlite3-dev libpng-dev zlib1g-dev
          buildozer init || true
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: LimbusTRPG-APK
          path: bin/*.apk
