name: Android CI with Discord Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3

    - name: JDK 설정
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 실행 권한 부여
      run: chmod +x ./gradlew

    - name: 디버그 APK 빌드
      run: ./gradlew assembleDebug

    - name: Discord로 APK 업로드
      run: |
        curl -X POST "https://discordapp.com/api/webhooks/1359871270597955726/BvQM8jibnBKQ6F5fCxVi_JA33kwDmGxhqi0WcNLzZ-TXa094pu1p57oN8Os1augHrvsd" \
        -F "payload_json={\"content\": \"✅ 새로운 LimbusTRPG APK가 빌드되었습니다!\"}" \
        -F "file=@app/build/outputs/apk/debug/app-debug.apk"